Feature157 component type such dialog
NiklasEckert/DigiProdVueWebUI pull request #18
Opened 2022-07-21 16:57 UTC by NiklasEckert

2022-07-21 17:47 UTC, jako264 commented on src/components/imacs_component/ComponentView.vue
>          name: "",
Müsste der Name hier nicht auch raus?

2022-07-21 17:48 UTC, jako264 commented on src/components/imacs_component/ComponentView.vue
>                name: "",
Wenn der oben raus muss, dann auch hier 😅

2022-07-21 17:50 UTC, jako264 approved these changes

2022-07-21 20:12 UTC, ichbinbenni requested changes

2022-07-21 20:12 UTC, ichbinbenni commented on src/components/imacs_component/ComponentView.vue
> +        filepath: "",
das 'P' muss groß, da es so vom server kommt. Ansonsten wird es nicht angezeigt.

2022-07-22 13:13 UTC, hamaximi approved these changes

2022-07-22 16:10 UTC, merged