Changed CompTypes to Article Description
NiklasEckert/DigiProdVueWebUI pull request #29
Opened 2022-07-29 13:30 UTC by hamaximi

Changed Component Types to Article Description in:
- DetailScreen ComponentType
-DetailScreen Component
-Navigation
-Search Dialog for ComponentTypes
-ComponentTypesView

2022-07-29 13:47 UTC, jako264 commented on src/router/index.js
> +    navCaption: "Article Description",
Ist das nicht zu lang?

2022-07-29 13:47 UTC, jako264 approved these changes

2022-07-29 13:51 UTC, hamaximi commented on src/router/index.js
> +    navCaption: "Article Description",
Ne passt genau rein, sah auf meinem Bildschirm zumindest passend aus.
<img width="189" alt="DigiProdNav" src="https://user-images.githubusercontent.com/51363557/181774801-23244bcf-ea87-4bad-8f80-3e22469ba21f.png">

2022-07-29 13:53 UTC, jako264 commented on src/router/index.js
> +    navCaption: "Article Description",
Okay alles klar 👍🏼

2022-07-29 14:01 UTC, jako264 approved these changes

2022-07-30 12:13 UTC, GolawskyM commented on src/components/util/dialogs/componentType_search_dialog/ComponentTypeSearchDialog.vue
> +    title="Choose a article description"
Streng genommen sollte es "Choose an article description" sein

2022-07-30 12:13 UTC, GolawskyM approved these changes

2022-08-01 14:24 UTC, ichbinbenni requested changes

2022-08-01 14:24 UTC, ichbinbenni commented on src/components/imacs_component/ComponentView.vue
> +              {{ this.componentType.name ?? "Choose article description of component" }}
Glaube hier müsste dass dann auch:
"Choose an article description of a component' sein

2022-08-04 12:49 UTC, hamaximi commented on src/components/imacs_component/ComponentView.vue
> +              {{ this.componentType.name ?? "Choose article description of component" }}
Ist gefixt

2022-08-04 12:51 UTC, ichbinbenni approved these changes

2022-08-04 13:18 UTC, merged