Update: AddSubcomponentSearchDialog
NiklasEckert/DigiProdVueWebUI pull request #31
Opened 2022-08-01 13:50 UTC by hamaximi

<img width="267" alt="SearchSubComponentErrorMessageDesign3" src="https://user-images.githubusercontent.com/51363557/182162640-18598d68-6e28-4a76-b52c-c3093099cd05.png">
 So sieht es jetzt aus. Bei Fehlermeldung automatisch eingeklappt, ansonsten offen mit allen Infos.

2022-08-01 14:14 UTC, ichbinbenni requested changes
Schon mal nen guter Anfang, hätte aber paar Änderungen:
Bugs:
- Ich kann trotz ausgegraut auf eine Zelle klicken.

Änderung für die UI:
- Bitte die Ordernumber nach rechts packen, dass die nach rechts alignt ist
- StatusText + Ein/ausklapp icon auf centerline mit QR-Code
- StatusText hat die gleiche Schriftgröße wie die attribute. 
- Ein/Ausklappding kann etwas größer
- Statustext auf ein dunkles grau setzen
- Wenn zwei Statusmeldungen vorliegen würde ich nur eine anzeigen nicht beide oder wenn man beide anzeigt Leerzeichen zwischen die.
- Abstand zwischen QR-Code und dem da drunter etwas größer.

- Mit dem ausgegraut und dem leichten Hintergrund ist sehr anstrengend zu gucken, da der Kontrast fehlt. Probier mal den Hintergrund der Table auch weiß zu machen

2022-08-01 19:20 UTC, ichbinbenni approved these changes

2022-08-02 10:57 UTC, jako264 approved these changes

2022-08-05 09:48 UTC, GolawskyM approved these changes

2022-08-05 12:15 UTC, merged